spring:
  profiles:
    active: local
  application:
    name: PJT-A-Server

  # mysql db 설정
  datasource:
    url: jdbc:mysql://localhost:3306/PJT_A_Server
    username: root
    password: '!ehgus9698'
    driver-class-name: com.mysql.cj.jdbc.Driver

  # jpa 설정
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategySnakeCaseImpl
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
  # 메일 관련 설정
  mail:
    host: smtp.gmail.com          # 구글 SMTP 서버 주소
    port: 587                     # 구글 SMTP 포트 번호
    username: do8351@gmail.com    # 사용자 이메일
    password: xshl wglj woiw mvkf # 사용자 앱 비밀번호
    properties:
      mail:
        smtp:
          auth: true              # 사용자 인증 여부
          timeout: 5000           # 이메일 전송 타임아웃 시간
          starttls:
            enable: true          # TLS를 통해 안전한 통신 사용 여부

  # 페이징 처리 page 0부터 시작
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000

server:
  port: 8081

# 실제로 나오는 로그
logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security.web : trace
#    org.hibernate.type : trace

